const actions = {
  SIGNUP: "SIGNUP",
  USERNAMEPASS: "USERNAMEPASS",
  LOGIN: "LOGIN",
  ADDMESSAGE: "ADDMESSAGE",
  USERS: "USERS",
  STATUS: "STATUS",
  GETUSER: "GETUSER",
  LOGOUT: "LOGOUT",
  DELETE: "DELETE",
  UPDATE: "UPDATE",
  //// chat
  MESSAGE: "MESSAGE"
};

export default actions;
